version: "3.9"
services:
  postgres:
    image: postgres
    container_name: database
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    container_name: web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/moatbuilders_task
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres:
